### ISSUE TITLE
Check how can we make our repository work in google colab.

### ISSUE THREAD

**Issue by b0nce** [OML-Team/open-metric-learning#146]
Problem is that now colab has only python 3.7 while our pip package supposed to work with 3.8+. If you instead try to install through `pip install git+...` it shows this error:
![IMG_20220917_121141_984](https://user-images.githubusercontent.com/27873390/190851677-a8ea5256-c9f2-4eac-b295-81b86f68339c.jpg)
Possible DOD: create working colab notebook and add it to README.

**Comment by churnikov** [comment]
Hi!

Can I work on this issue?

**Comment by AlekseySh** [comment]
@churnikov Yes, sure. Recently we added the support of python 3.7, so, we expect the repo to work in Google Collab now. So, it would be very helpful if you could paste the examples from our readme to google collab and check them. If they don't work, then, yes, we need to figure out how to solve the problem. Thank you in advance!

**Comment by churnikov** [comment]
Okay, so I was able to create a link to colab notebook and make a button for it.

There were some problems with dependencies, but I made a workaround for now

https://github.com/churnikov/open-metric-learning/tree/colab-notebook

https://colab.research.google.com/github/churnikov/open-metric-learning/blob/colab-notebook/examples/intro.ipynb

But it would probably be nice to add some more details to this notebook as it seems rather empty right now

**Comment by AlekseySh** [comment]
@churnikov thank you a lot, I think we will change the versions of the libraries in OML according to your notebook.
I will add the examples by myself to collab since it is related to the google account, so, I guess, It's better to use mine. We already have [issue](https://github.com/OML-Team/open-metric-learning/issues/176) for that. So, this issue was only to check if it works in collab or not, and now we have an answer thank to you :)

**Comment by AlekseySh** [comment]
If you want to contribute something to our repo, I would suggest you to consider this issue: https://github.com/OML-Team/open-metric-learning/issues/85 or this https://github.com/OML-Team/open-metric-learning/issues/108
