### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by tataganesh** [OML-Team/open-metric-learning#177]
Some guidelines for contributing to the project would be useful for working on the open issues.

**Comment by AlekseySh** [comment]
@tataganesh thank you for the advice, we will add it. But now we already marked good first issues with the tag `good first issue`

**Comment by tataganesh** [comment]
Thanks @AlekseySh . Do you expect the pull requests to have a certain format (i.e what should one cover as part of the description)? Are there any specific tests to be run before making a PR?

**Comment by AlekseySh** [comment]
@tataganesh It heavily depends on the task. I would say if you feel the task is big enough and non-trivial, it's better to get in contact with core contributors and discuss the content of PR in advance. It may be done in comments for the corresponding issue.

We expect that the new code must be covered in the same PR. The exact content of tests also should be discussed in the same way.

For your convenience, you may run tests locally (see `Makefile`), but it's not obligatory since we have CI/CD system which will run tests anyway before merging. But the developing process is much easier if one runs tests automatically. 

I'll structure this in the contribution guide later on.

**Comment by AlekseySh** [comment]
@tataganesh By the way, do you have in mind some features that you want to contribute to our project? We are really welcome to the new developers!

**Comment by tataganesh** [comment]
Thank you for the detailed explanation @AlekseySh ! I am new to metric learning, so I will take a look at the issues and see if I can make any contributions. Thanks once again!

**Comment by AlekseySh** [comment]
I will keep it open until I add the contributing guide.
