### ISSUE TITLE
The validation dataset size should not be too large ?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#348]
If the validation dataset has `n` samples with `is_query=True` and `is_gallery=True`,  in `compute_metrics` function, it will compute a `nxn` distance matrix, whose computation are memory-consuming and time-consuming. In my case, the validation dataset has 2w samples, the process seems to get stuck for many minutes when validating.  So the validation dataset size should not be too large ?

**Comment by AlekseySh** [comment]
You are right about the idea of the `n x n` matrix. The biggest dataset that we use in our research is Stanford Online Products, which has 60k images in test, so, it produces 60k x 60k matrix.

**Comment by AlekseySh** [comment]
If you have a custom dataset, I may recommend you split the test set into queries and galleries without overlapping, it will reduce computational cost.

**Comment by AlekseySh** [comment]
There is an advanced option: use kNN instead of explicitly calculating `n x n` matrix. Like in the `Using a trained model for retrieval` example. But this approach is not implemented in `EmbeddingMetrics` (we simply create a distances matrix there). So, you need to modify the existing library code or propose your own implementation for the metrics.

**Comment by PapaMadeleine2022** [comment]
> If you have a custom dataset, I may recommend you split the test set into queries and galleries without overlapping, it will reduce computational cost.

That is good advice.
