### ISSUE TITLE
How to enable Neptune logging?

### ISSUE THREAD

**Issue by SiddhantSadangi** [OML-Team/open-metric-learning#383]
Hello,

The [Logging & Visualization](https://open-metric-learning.readthedocs.io/en/latest/oml/logging.html#logging-in-pipelines) guide for Neptune mentions that the `neptune_project` has to be set in a config file. 

Which config file is this? I tried to run the training example with the `NEPTUNE_PROJECT` and `NEPTUNE_API_TOKEN` env variables set, but it didn't create any run on Neptune, nor threw any warning/error.

**Comment by AlekseySh** [comment]
Hello, @SiddhantSadangi 

You are right, a config file for train, for example, this one: https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/features_extraction/extractor_cars/train_cars.yaml

The problem is that the instruction says: `To activate Neptune you need to set neptune_project in a config file and provide your NEPTUNE_API_TOKEN as env variable.` So, one value you need to set in the config, the other one as an env variable.

Does it work now?

**Comment by SiddhantSadangi** [comment]
I am afraid not :(

It is an issue with the dataset. The link to download the CARS196 dataset in the [Dataset converters readme](https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/datasets_converters/README.md) is broken.
I was able to download the dataset from Kaggle, but the converter expects a file that my dataset does not have:

```
> python ../datasets_converters/convert_cars.py --dataset_root=data/CARS196                                          ​ ✘ ╱  py38 ╱ 2s 790ms  ╱  65 ╱ 12:26:13  
Cars dataset preparation started...
Traceback (most recent call last):
  File "../datasets_converters/convert_cars.py", line 108, in <module>
    main()
  File "../datasets_converters/convert_cars.py", line 100, in main
    df = build_cars196_df(args.dataset_root, args.no_bboxes)
  File "../datasets_converters/convert_cars.py", line 46, in build_cars196_df
    assert file.is_file(), f"File {file} does not exist."
AssertionError: File data\CARS196\devkit\cars_meta.mat does not exist.
```

It is the same with the CUB_200_2011 dataset as well:
```
> python ../datasets_converters/convert_cub.py --dataset_root=data/CUB_200_2011                                      ​ ✘ ╱  py38 ╱ 1s 881ms  ╱  65 ╱ 12:34:43  
CUB200 2011 dataset preparation started...
Traceback (most recent call last):
  File "../datasets_converters/convert_cub.py", line 114, in <module>
    main()
  File "../datasets_converters/convert_cub.py", line 106, in main
    df = build_cub_df(args.dataset_root, args.no_bboxes)
  File "../datasets_converters/convert_cub.py", line 38, in build_cub_df
    assert file.is_file(), f"File {file} does not exist."
AssertionError: File data\CUB_200_2011\images.txt does not exist.
```

**Comment by AlekseySh** [comment]
@SiddhantSadangi Looks like they moved the CARS dataset, again. I will take care of it...

As for CUB, I downloaded it and there is a `images.txt` file inside.

CUB dataset has a nested structure: there is `CUB_200_2011` subfolder in the original downloaded `CUB_200_2011` folder. You need to work with this inner folder.

**Comment by AlekseySh** [comment]
@SiddhantSadangi Thanks for sharing! As for Hydra, it's because they recently changed the behaviour regarding work dir.
As for the permission error -- have you tried to run `chmod` command? 

I think it may be better to have a call together and check what is going on. I messaged you on LinkedIn so we can have a call if it's fine for you.

**Comment by AlekseySh** [comment]
Discussed offline.
