### ISSUE TITLE
Postprocess on gpu

### ISSUE THREAD

**Issue by june94** [OML-Team/open-metric-learning#394]
Thank you for your work!

Could you please guide how to run postprocess on gpu (how to create right config)? I use provided weights (for both extractor and processor) to validate my dataset and set _accelerator: gpu_, then extractor runs on gpu, but processor is still on cpu.

**Comment by june94** [comment]
This could be my misunderstanding - I made this conclusion based on this progress bar info with "cpu" label (image attached 
![image](https://github.com/OML-Team/open-metric-learning/assets/19962166/9b92f511-0527-4c6a-a6b0-e3f55c30c50f)
) and compared time of postprocess inference with extractor inference (same architecture used) - the first one takes 2-3 times longer. If it's normal behavior, does it mean, that some additional postprocess on cpu (kind of distances rearrangement) take so much time?

**Comment by AlekseySh** [comment]
Hm, thank you! It's wierd. I will take a look.

> the first one takes 2-3 times longer

The time needed for extractor is O(N), where N is the size of your validation dataset.
The time needed for postprocessor is O(N_queries * top_k). The postprocessor's inference itself is also longer since we concatenate images (roughly ~4 times). 

So, what are your N, N_queries, top_k? 

Anyway, for most of the datasets postprocessing takes longer than extraction stage. So, 2-3 times longer seems okay, but if both of them on GPU. So, I surprised that difference is not as big that I expected. But probably your dataset is just as unique.

**Comment by AlekseySh** [comment]
I took a look. Everything works fine for me when I set `gpu` in a config file. 

<img width="827" alt="Screenshot 2023-06-17 at 14 10 06" src="https://github.com/OML-Team/open-metric-learning/assets/20143575/bdd5b362-a890-44ee-8a12-dc9abd80c580">

**Comment by AlekseySh** [comment]
@june94 , Is your Cuda available? If not, your device could be selected by default as cpu. Please, check it out

**Comment by AlekseySh** [comment]
@june94 if there are any updates here?

**Comment by AlekseySh** [comment]
Close due to inactivity
