### ISSUE TITLE
Training example for ConcatSiamese 

### ISSUE THREAD

**Issue by taaresh7** [OML-Team/open-metric-learning#521]
Hi, 

Thanks for the awesome library!! 

I trained a VIT model with triplet loss, now I am thinking of training a siamese network also, I see that the library has **ConcatSiamese** model class, But how should I get started with the training the ConcatSiamese, any training example or documentation for this. 

Thanks!!

**Comment by AlekseySh** [comment]
Hi!

Thank you for using OML!

In the context of the library we used ConcatSiamese as a re-ranking model that follows vanilla vector search:
https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/postprocessing/pairwise_postprocessing
You can get more details from the paper we published (the link is also there). 

There is no example for dedicated ConcatSiamese model (because it's not really useful in real life applications since it has quadratic complexity). But if you still want to train this model in an independent context, you can get some inspiration from this code:
https://github.com/OML-Team/open-metric-learning/blob/main/oml/lightning/pipelines/train_postprocessor.py#L142C30-L142C47

**Comment by AlekseySh** [comment]
@taaresh7 by the way, if you are affiliated with some company or university, I will highly appreciate if you allow us to add its logo to the "trusted by" section in readme.

**Comment by taaresh7** [comment]
Thanks for the quick reply @AlekseySh,

Currently everything is in R&D, if we end up using the library in any way, I will surely let you know.

**Comment by AlekseySh** [comment]
@taaresh7 The section named "trusted by", not "used by". So, it's not necessary to put the model into production to get there. The fact that you just were playing with the model is enough :)
