### ISSUE TITLE
An error will be reported during the metric calculation process of self-created data set

### ISSUE THREAD

**Issue by snow-wind-001** [OML-Team/open-metric-learning#562]
![image](https://github.com/OML-Team/open-metric-learning/assets/33013904/4533e622-2d96-475f-8591-e2dfbdd0be37)
We copied the format of the cars196 data set and made our own data set, with a total of 172 classes and a total of 450,000 pieces of data. The training process goes very smoothly, but when calculating indicators after performing val operations, a large amount of memory will be occupied until it crashes. Please help me solve the problem.

**Comment by snow-wind-001** [comment]
@chang48 @dapladoc @churnikov @alexmelekhin

**Comment by AlekseySh** [comment]
Hi, @snow-wind-001 

It's a known problem. The current implementation requires storing 450k x 450k floats in your memory. Right now I'm working on the solution to make it memory optimized. It will be released soon with OML 3.0 (in a week or max two).

You may wait or you may do the following:
Split your validation set into non overlapping queries and galleries (for CARS they do overlap because `is_query == is_gallery == True`). The idea is you may use 50k items as queries and 400k as galleries. You may use DeepFashion as a reference because it has the same logic in query gallery split. It may be also convinient to use this [function](https://github.com/OML-Team/open-metric-learning/blob/749c326c0943e668414f974b7e6c439c8d884de9/oml/utils/dataframe_format.py#L25) to check the format of the resulted dataframe. More info on datasets [here](https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/datasets_converters).
